### ISSUE TITLE
`xsi:type` attribute on command element

### ISSUE THREAD

**Issue by reckart** [antleb/omtd-registry-api#7]
@pennyl67 @courado do you have any idea why the`command` element receives a `xsi:type` attribute? No other elements has it.

```
    <ns1:distributionInfos>
      <ns1:componentDistributionInfo>
        <ns1:command xmlns:xs="http://www.w3.org/2001/XMLSchema" xsi:type="xs:string">gate.creole.POSTagger</ns1:command>
        <ns1:operatingSystems>
          <ns1:operatingSystem>os-independent</ns1:operatingSystem>
        </ns1:operatingSystems>
      </ns1:componentDistributionInfo>
    </ns1:distributionInfos>
```

**Comment by courado** [comment]
Because in the xsd command has no type but the java classes know it's a string.

**Comment by reckart** [comment]
@courado @pennyl67 - so this should be fixed in the XSD then?

**Comment by pennyl67** [comment]
It's one of the things that Stefanos has spotted and it's fixed now. I suppose the java classes must be regenerated to reflect the change.
